<?php
/**
 * Render the Configuration123 display block using the site's current settings.
 *
 * @var array<string, mixed> $attributes Block attributes.
 *
 * @package Configuration123
 */

declare(strict_types=1);

defined( 'ABSPATH' ) || exit;

$view        = sanitize_key( (string) ( $attributes['view'] ?? 'site-identity' ) );
$compact     = ! empty( $attributes['compact'] );
$show_labels = ! isset( $attributes['showLabels'] ) || ! empty( $attributes['showLabels'] );
$frontend    = new \Configuration123\Frontend();

switch ( $view ) {
	case 'site-identity':
		$site_name    = trim( (string) \Configuration123\get_value( 'site_name', get_bloginfo( 'name' ) ) );
		$site_tagline = trim( (string) \Configuration123\get_value( 'site_tagline', get_bloginfo( 'description' ) ) );
		$content      = '';

		if ( '' !== $site_name ) {
			$content .= '<strong class="configuration123-site-identity__name">' . esc_html( $site_name ) . '</strong>';
		}
		if ( '' !== $site_tagline ) {
			$content .= '<span class="configuration123-site-identity__tagline">' . esc_html( $site_tagline ) . '</span>';
		}
		if ( '' !== $content ) {
			$content = '<div class="configuration123-site-identity">' . $content . '</div>';
		}
		break;

	case 'owner-profile':
		$content = $frontend->profile_shortcode(
			array(
				'type'        => 'owner',
				'show_labels' => $show_labels ? 'true' : 'false',
			)
		);
		break;

	case 'designer-profile':
		$content = $frontend->profile_shortcode(
			array(
				'type'        => 'designer',
				'show_labels' => $show_labels ? 'true' : 'false',
			)
		);
		break;

	case 'owner-card':
		$content = $frontend->owner_card_shortcode( array( 'compact' => $compact ? 'true' : 'false' ) );
		break;

	case 'contact':
		$content = $frontend->contact_shortcode( array( 'compact' => $compact ? 'true' : 'false' ) );
		break;

	case 'location':
		$content = $frontend->location_shortcode();
		break;

	case 'services':
		$content = $frontend->services_shortcode();
		break;

	case 'socials':
		$content = $frontend->socials_shortcode();
		break;

	case 'attribution':
		$content = $frontend->attribution_shortcode();
		break;

	case 'copyright':
		$content = $frontend->copyright_shortcode();
		break;

	default:
		$content = '';
}

if ( '' === trim( $content ) ) {
	return;
}

$wrapper_attributes = get_block_wrapper_attributes(
	array(
		'class' => 'configuration123-display configuration123-display--' . $view . ( $compact ? ' is-compact' : '' ),
	)
);
?>
<div <?php echo $wrapper_attributes; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Generated by WordPress. ?>><?php echo wp_kses_post( $content ); ?></div>
